[package]
name = "watchdog"
version = "0.1.3"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
dotenvs = "0.1.0"
reqwest = { version = "0.12.15", features = ["json"] }
serde_json = "1.0.140"
tokio = { version = "1.44.2", features = ["full"] }
