name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "*25 * * * *"

env:
  CARGO_TERM_COLOR: always
  WEBHOOK: ${{ secrets.WEBHOOK }}
  MENTION: ${{ secrets.MENTION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Cache compiled code
      uses: actions/cache@v4
      id: cache-rust
      with:
        path: ${{ github.workspace }}/target/
        key: ${{ hashFiles('Cargo.lock', 'src/**') }}
    - name: Run periodically
      run: cargo run --release --verbose
