name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "25 * * * *"

env:
  CARGO_TERM_COLOR: always
  WEBHOOK: ${{ secrets.WEBHOOK }}
  MENTION: ${{ secrets.MENTION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Periodically check Natsuki
      run: cargo run --release --verbose
